version: '3.8'

# Define the services (containers) that will be run
services:
  # First service: Flask app
  flask_app:
    # Build the image from the Dockerfile in the parent directory

    # Set the name of the resulting image
    image: ameer510/wog_test
    # Mount local files/directories as volumes in the container


    # Expose the container's port 5000 to host port 8777
    ports:
      - "8777:5000"
    # Set environment variables for the container

    # Start the Flask app with "flask run" command
    command: [ "flask", "run",]
    # Connect the container to a custom network with a static IP address
